replicaCount: 1

image:
  repository: registry.kube-system.svc.cluster.local:5000/newsrec-app
  tag: staging-1.0.0

service:
  port: 8081
  externalIP: ""   # Placeholder for the external IP of the service

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "128Mi"

